<?php
/**
 * ResultOfPageResponseOfMessageObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DaDaPushClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DaDaPushClient;

use PHPUnit\Framework\TestCase;

/**
 * ResultOfPageResponseOfMessageObjectTest Class Doc Comment
 *
 * @category    Class
 * @description ResultOfPageResponseOfMessageObject
 * @package     DaDaPushClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResultOfPageResponseOfMessageObjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResultOfPageResponseOfMessageObject"
     */
    public function testResultOfPageResponseOfMessageObject()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "errmsg"
     */
    public function testPropertyErrmsg()
    {
    }
}
