<?php
/**
 * DaDaPushMessageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DaDaPushClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DaDaPushClient;

use \DaDaPushClient\Configuration;
use \DaDaPushClient\ApiException;
use \DaDaPushClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DaDaPushMessageApiTest Class Doc Comment
 *
 * @category Class
 * @package  DaDaPushClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DaDaPushMessageApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMessage
     *
     * push Message to a Channel.
     *
     */
    public function testCreateMessage()
    {
    }

    /**
     * Test case for deleteMessage
     *
     * delete a Channel Message.
     *
     */
    public function testDeleteMessage()
    {
    }

    /**
     * Test case for getMessage
     *
     * get a Channel Message.
     *
     */
    public function testGetMessage()
    {
    }

    /**
     * Test case for getMessages
     *
     * get Message List.
     *
     */
    public function testGetMessages()
    {
    }
}
